name: Checkmarx SAST Scan
on:
  push:
    branches:
      - main

jobs:
  checkmarx-sast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx CxSAST Scan
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.2
        with:
          project: ${{ github.event.repository.name }}
          team: /CxServer/Checkmarx/GitHub Actions
          preset: ASA-Premium
          incremental: false
          checkmarx_url: ${{ secrets.CHECKMARX_URL }}
          checkmarx_username: ${{ secrets.CHECKMARX_USER }}
          checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
          checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
          scanners: sast
          params: --cx-flow.bug-tracker=NONE --checkmarx.exclude-files="README.md" --checkmarx.exclude-folders="docs,tests" --checkmarx.configuration="Improved Scan Flow" --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }} -logging.level.com.checkmarx.flow=debug --logging.level.com.checkmarx.sdk.service=debug
