name: Checkmarx SAST Scan
on:
  push:
    branches:
      - main

jobs:
  checkmarx-sast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx CxSAST Scan
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.2
        with:
          project: ${{ github.event.repository.name }}
          CHECKMARX_EXCLUDE_FILES: "README.md"
          CHECKMARX_EXCLUDE_FOLDERS: "src"
          team: /CxServer/Checkmarx/GitHub Actions
          preset: ASA-Premium
          checkmarx_url: ${{ secrets.CHECKMARX_URL }}
          checkmarx_username: ${{ secrets.CHECKMARX_USER }}
          checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
          checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
          scanners: sast
          params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }}
