name: Checkmarx SAST - Daily Scan
on:
  schedule:
    - cron: '*/5 * * * *'
    # Every day at noon
    #- cron:  '0 12 * * *'

jobs:
  checkmarx-sast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Checkmarx CxSAST Scan
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.3
        with:
          project: ${{ github.repository.name }}-${{ github.ref_name }}
          team: /CxServer/Checkmarx/GitHub Actions
          preset: Checkmarx Express
          incremental: false
          checkmarx_url: ${{ secrets.CHECKMARX_URL }}
          checkmarx_username: ${{ secrets.CHECKMARX_USER }}
          checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
          checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
          scanners: sast
          params: --cx-flow.bug-tracker=NONE --checkmarx.exclude-files=*min.js,*Test.java --checkmarx.exclude-folders=docs,test,tests --checkmarx.settings-override=true --namespace=${{ github.repository_owner }} --repo-name=${{ github.repository.name }} --branch=${{ github.ref }} -logging.level.com.checkmarx.flow=debug --logging.level.com.checkmarx.sdk.service=debug
