name: Checkmarx SAST - On Push Scan
on:
  push:
    branches:
      - main

jobs:
  checkmarx-sast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Set Checkmarx Project Configuration"
        env:
          cx-sast-project-configuration: 'Improved Scan Flow'
          cx-sast-project-exclude-files: '*min.js,*Test.java'
          cx-sast-project-exclude-folders: 'docs,test,tests'
          cx-sast-project-preset: 'Checkmarx Express'
          cx-sast-project-team: '/CxServer/Checkmarx/GitHub Actions'
        run: echo "The variables have been defined."
      - name: Checkmarx CxSAST Scan
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.3
        with:
          project: ${{ github.event.repository.name }}-${{ github.ref_name }}
          bug_tracker: NONE
          team: ${{ env.cx-sast-project-team }}
          preset: ${{ env.cx-sast-project-preset }}
          incremental: true
          checkmarx_url: ${{ secrets.CHECKMARX_URL }}
          checkmarx_username: ${{ secrets.CHECKMARX_USER }}
          checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
          checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
          scanners: sast
          params: --checkmarx.configuration=${{ env.cx-sast-project-configuration }} --checkmarx.exclude-files=${{ env.cx-sast-project-exclude-files }} --checkmarx.exclude-folders=${{ env.cx-sast-project-exclude-folders }} --checkmarx.settings-override=true --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }} -logging.level.com.checkmarx.flow=debug --logging.level.com.checkmarx.sdk.service=debug
